apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coming-soon-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: coming-soon.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coming-soon
                port:
                  number: 80
